### ISSUE TITLE
une idée pour fermer la fenêtre déjà ouverte

### ISSUE THREAD

**Issue by cyroul82** [vlad06/MaquetteABI#1]
public partial class frmGestionClient : Form
{
    private frmAjoutClient frmAjout;
--> //Ajoute un dictionnary
--> private Dictionary<Int32, frmVisuClient> listFrmViuClient = new Dictionary<Int32, frmVisuClient>();

public frmGestionClient()
{
InitializeComponent();
this.btnDetailClient.Enabled = false;
this.btnVoirContact.Enabled = false;
}

    private void afficheDetailClient()
    {
        if (this.grdClient.CurrentRow != null)
        {
            int iClient = this.grdClient.CurrentRow.Index;//récupère l'indice du client cliqué dans la datagrid
            Client leClient = Donnees.ArrayClient[iClient];
            if (!isFormOpen())  //si la form client n'est pas encore ouverte
            {
                frmVisuClient frmVisu = new frmVisuClient(leClient); //on crée une instance de la form client
                Donnees.ArrayfrmVisu.Add(frmVisu);//TODO, arriver à extraire la ref du form pour comparaison lors de la suppression d'une ligne
                                                  //dans le datagrid afin de fermer la fenêtre correspondante à la ligne supprimée
                                                  //
                                                  //
                                                  //
                                                  //
                                                  //
                                                  //
                                                  //
----> //ajoute le form visu à la liste
-----> listFrmViuClient.Add(leClient.IdClient, frmVisu);

                frmVisu.Show(); //on l'affiche
                frmVisu.TopMost = true; //on force la form client au premier plan
                //this.afficheClients();  //on met à jour la datagrid
                Donnees.ArrayFrmClientOpened.Add(leClient.IdClient);    //on ajoute à la liste des fenêtres ouverte l'id du client affiché
            } else
            {
                MessageBox.Show("Cette fenêtre client est déjà ouverte", "Attention", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }

    private bool isFormOpen()
    {
        int iClient = this.grdClient.CurrentRow.Index;
        Client leClient = Donnees.ArrayClient[iClient];
        for (int i = 0; i < Donnees.ArrayFrmClientOpened.Count; i++)
        {
            if (Donnees.ArrayFrmClientOpened[i] == leClient.IdClient)
            {
                return true;
            }
        }
        return false;
    }

    private void btnSupprimerClient_Click(object sender, EventArgs e)
    {
        DialogResult dr = MessageBox.Show("Etes-vous sûr de vouloir supprimer le client sélectionné ?", "ATTENTION",
            MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);
        if (dr == DialogResult.OK)
        {
            if (isFormOpen())
            {
                
            }
            
            int iClient = this.grdClient.CurrentRow.Index;
            Client leClient = Donnees.ArrayClient[iClient];
---> //Ferme la fenêtre
if (listFrmViuClient.ContainsKey(leClient.IdClient)){
frmVisuClient f = listFrmViuClient[leClient.IdClient];
f.Close();
}
--->
Donnees.ArrayFrmClientOpened.Remove(leClient.IdClient);
Donnees.ArrayClient.Remove(leClient);
afficheClients();
}
}

**Comment by vlad06** [comment]
c'est bon je viens de l'implémenter, merci beaucoup pour la solution^^
